base_url = "https://me.shoyuvanilla.net"
title = "Shoyu Vanilla"

compile_sass = true

highlight_code = true

build_search_index = false

check_external_links = true

taxonomies = [
    {name = "tags", rss = true}
]

[extra]
show_word_count = true
show_reading_time = true

date_format = "%a %b %e, %Y"

home = "home"

sam_menu = [
    { text = "about", link = "/about" },
    { text = "games", link = "/games" },
    { text = "others", link = "/others" }
]

sam_bottom_menu = true

[extra.sam_footer]
text = "Shoyu Vanilla"
